### ISSUE TITLE
panic: fork/exec /tmp/tmpMarp3329840233: permission denied

### ISSUE THREAD

**Issue by yyh0808** [williamfzc/chat-gpt-ppt#8]
请问这个应该怎么解决。需要给tmp权限？

**Comment by williamfzc** [comment]
> 请问这个应该怎么解决。需要给tmp权限？

啥系统呀。昨晚太晚了在mac上测完直接上了
原理是内置了marp-cli，会先写入tmp再运行

**Comment by williamfzc** [comment]
> 请问这个应该怎么解决。需要给tmp权限？

找个mac跟linux试了下都OK，windows倒确实有点问题。
linux给了tmp权限就可了。

**Comment by yyh0808** [comment]
我是mac intel芯片，一直报错这个，用sudo也是一样。token我直接填的付费api，貌似能done，就是这个/tmp绕不过去

**Comment by williamfzc** [comment]
算了这个embed方法实在是有点hack，晚上我改下打包方式

**Comment by williamfzc** [comment]
发了 v0.4.0，可以试试。

先移除了硬打包的marp，改用 remark 来拼接 ppt。二进制包也更小了。
